CHARACTERS = {
    "ryu": {
        "id": 1,
        "name": "Ryu Watanabe",
        "character_class": "Fighter/Samurai",
        "race": "Human",
        "hp": 31,
        "max_hp": 31,
        "armor_class": 15,
        "strength": 16,
        "dexterity": 14,
        "constitution": 12,
        "intelligence": 10,
        "wisdom": 10,
        "charisma": 12,
        "advantage_skills": ["athletics", "intimidation"],
    },
    "ayane": {
        "id": 2,
        "name": "Ayane",
        "character_class": "Cleric/Light Domain",
        "race": "Human",
        "hp": 24,
        "max_hp": 24,
        "armor_class": 16,
        "strength": 10,
        "dexterity": 12,
        "constitution": 12,
        "intelligence": 12,
        "wisdom": 16,
        "charisma": 14,
        "advantage_skills": ["insight", "religion"],
    },
}
