CHARACTERS = {
    "ayane": {
        "id": 1,
        "name": "Ayane",
        "character_class": "Fighter/Samurai",
        "race": "Human",
        "hp": 28,
        "max_hp": 28,
        "armor_class": 16,
        "strength": 16,
        "dexterity": 14,
        "constitution": 12,
        "intelligence": 10,
        "wisdom": 10,
        "charisma": 12,
        "advantage_skills": ["deception", "insight"],
    },
    "johan": {
        "id": 2,
        "name": "Johan",
        "character_class": "Ranger",
        "race": "Human",
        "hp": 24,
        "max_hp": 24,
        "armor_class": 14,
        "strength": 12,
        "dexterity": 16,
        "constitution": 12,
        "intelligence": 10,
        "wisdom": 14,
        "charisma": 10,
        "advantage_skills": [],
    },
}
